print("Contact Form")
fullname=input("Enter Your Full Name")
Age=input("Enter your Age")
Course=input("Enter Your Course")
Contact=input("Enter Your Contact No")
print("The name you had entered is",full_name)
print("The age you had entered is", Age)
print("The course you had entered is",Course)
print("The contact you had entered is",Contact)
